development:
  # logger: false
  host: localhost
  port: 27017
  database: mongoid_demo

replica_set:
  hosts:
    - - localhost
      - 27021
    - - localhost
      - 27022
    - - localhost
      - 27023
  read: :secondary
  database: replication_demo

master_slave:
  host: localhost
  port: 27018
  slaves:
    - host: localhost
      port: 27019
    - host: localhost
      port: 27020
  database: master_slave_demo

